name: CD

on:
  push:
    branches:
      - main
jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      # building and pushing the image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/teqaction-fe:${{ github.sha }}
      - name: SSH into VM and deploy container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_PVT_KEY}}
          script: |
            docker pull ${{secrets.DOCKER_USERNAME}}/teqaction-fe:${{ github.sha }}
            docker stop teqaction-fe || true
            docker rm teqaction-fe || true
            docker run -d --name teqaction-fe -p 3000:3000 ${{secrets.DOCKER_USERNAME}}/teqaction-fe:${{github.sha}}
  